export type HistoryDifficulty = 'easy' | 'hard';

export type HistoryQuestion = {
  id: number;
  category: string;
  question: string;
  answers: string[];
  correct: number;
  difficulty: HistoryDifficulty;
  source: string;
  explanation: string;
};

type HistoryEvent = {
  date: string;
  event: string;
  place: string;
  cause: string;
  consequence: string;
  significance: string;
};

export const HISTORY_TOPICS = [
  { key: 'Geschichte Erster Weltkrieg', label: 'Erster Weltkrieg' },
  { key: 'Geschichte Zweiter Weltkrieg', label: 'Zweiter Weltkrieg' },
  { key: 'Geschichte Tschetschenien', label: 'Tschetschenische Geschichte' },
  { key: 'Geschichte Japan', label: 'Japanische Geschichte' },
] as const;

const uniqueOptions = (correct: string, values: string[], seed: number) => {
  const candidates = [...new Set(values.filter(value => value !== correct))];
  const picked: string[] = [];
  for (let offset = 0; offset < candidates.length && picked.length < 3; offset += 1) {
    const value = candidates[(seed + offset * 5) % candidates.length];
    if (!picked.includes(value)) picked.push(value);
  }
  return [correct, ...picked].slice(0, 4);
};

const explanationFor = (item: HistoryEvent) =>
  `${item.event} (${item.date}, ${item.place}). Ursache: ${item.cause}. Folge: ${item.consequence}. Bedeutung: ${item.significance}.`;

const buildTopic = (
  events: HistoryEvent[],
  category: string,
  baseId: number,
  easyTarget: number,
  hardTarget: number,
  source: string,
): HistoryQuestion[] => {
  const easy: HistoryQuestion[] = [];
  const hard: HistoryQuestion[] = [];
  let id = baseId;

  events.forEach((item, index) => {
    easy.push({ id: id++, category, question: `Wann fand folgendes Ereignis statt: ${item.event}?`, answers: uniqueOptions(item.date, events.map(event => event.date), index), correct: 0, difficulty: 'easy', source, explanation: explanationFor(item) });
  });
  events.forEach((item, index) => {
    easy.push({ id: id++, category, question: `Welches Ereignis gehört zum Zeitpunkt ${item.date}?`, answers: uniqueOptions(item.event, events.map(event => event.event), index + 3), correct: 0, difficulty: 'easy', source, explanation: explanationFor(item) });
  });
  events.forEach((item, index) => {
    easy.push({ id: id++, category, question: `Wo spielte sich das Ereignis „${item.event}“ hauptsächlich ab?`, answers: uniqueOptions(item.place, events.map(event => event.place), index + 7), correct: 0, difficulty: 'easy', source, explanation: explanationFor(item) });
  });
  events.forEach((item, index) => {
    easy.push({ id: id++, category, question: `Welche unmittelbare Folge hatte „${item.event}“?`, answers: uniqueOptions(item.consequence, events.map(event => event.consequence), index + 11), correct: 0, difficulty: 'easy', source, explanation: explanationFor(item) });
  });
  events.forEach((item, index) => {
    hard.push({ id: id++, category, question: `Welche Ursache oder Vorgeschichte trug wesentlich zu „${item.event}“ bei?`, answers: uniqueOptions(item.cause, events.map(event => event.cause), index + 13), correct: 0, difficulty: 'hard', source, explanation: explanationFor(item) });
  });
  events.forEach((item, index) => {
    hard.push({ id: id++, category, question: `Warum ist „${item.event}“ historisch besonders bedeutsam?`, answers: uniqueOptions(item.significance, events.map(event => event.significance), index + 17), correct: 0, difficulty: 'hard', source, explanation: explanationFor(item) });
  });

  return [...easy.slice(0, easyTarget), ...hard.slice(0, hardTarget)];
};

const WWI_EVENTS: HistoryEvent[] = [
  { date:'28. Juni 1914', event:'Attentat von Sarajevo', place:'Sarajevo', cause:'Nationalistische Spannungen auf dem Balkan und der Besuch des österreichisch-ungarischen Thronfolgers in Sarajevo', consequence:'Der Tod Franz Ferdinands löste die Julikrise aus', significance:'Das Attentat war der unmittelbare Auslöser der diplomatischen Eskalation zum Ersten Weltkrieg' },
  { date:'23. Juli 1914', event:'Österreich-ungarisches Ultimatum an Serbien', place:'Wien und Belgrad', cause:'Österreich-Ungarn wollte nach dem Attentat starken Druck auf Serbien ausüben', consequence:'Serbien akzeptierte viele, aber nicht alle Forderungen', significance:'Das Ultimatum verschärfte die Julikrise entscheidend' },
  { date:'28. Juli 1914', event:'Österreich-Ungarn erklärt Serbien den Krieg', place:'Wien', cause:'Die unvollständige Annahme des Ultimatums durch Serbien und die Julikrise', consequence:'Der Krieg zwischen Österreich-Ungarn und Serbien begann', significance:'Die Kriegserklärung setzte die Bündnismechanismen Europas in Bewegung' },
  { date:'1. August 1914', event:'Deutschland erklärt Russland den Krieg', place:'Berlin', cause:'Russlands Mobilmachung im Zusammenhang mit dem Konflikt zwischen Österreich-Ungarn und Serbien', consequence:'Deutschland und Russland traten offen in den Krieg ein', significance:'Der regionale Balkankonflikt weitete sich zu einem europäischen Großkrieg aus' },
  { date:'4. August 1914', event:'Deutscher Einmarsch in Belgien und britischer Kriegseintritt', place:'Belgien und London', cause:'Der deutsche Operationsplan sah einen Vormarsch durch das neutrale Belgien gegen Frankreich vor', consequence:'Großbritannien erklärte Deutschland den Krieg', significance:'Die Verletzung der belgischen Neutralität weitete den Krieg weiter aus' },
  { date:'6. bis 12. September 1914', event:'Erste Schlacht an der Marne', place:'Nordostfrankreich', cause:'Der deutsche Vormarsch auf Paris sollte die französischen Armeen schnell schlagen', consequence:'Der deutsche Vormarsch wurde gestoppt und die Front stabilisierte sich', significance:'Die Schlacht trug zum Übergang in den langwierigen Stellungskrieg im Westen bei' },
  { date:'19. Oktober bis 22. November 1914', event:'Erste Schlacht bei Ypern', place:'Flandern', cause:'Beide Seiten versuchten nach der Marne die offene Nordflanke zu umgehen', consequence:'Keine Seite erzielte einen entscheidenden Durchbruch', significance:'Die Front erstarrte zunehmend zu einem zusammenhängenden Grabensystem' },
  { date:'5. November 1914', event:'Britannien und Frankreich erklären dem Osmanischen Reich den Krieg', place:'London und Paris', cause:'Das Osmanische Reich war an der Seite der Mittelmächte in den Krieg eingetreten', consequence:'Neue Fronten entstanden im Nahen Osten und an den Meerengen', significance:'Der Krieg weitete sich stärker über Europa hinaus aus' },
  { date:'4. Februar 1915', event:'Deutschland kündigt verschärften U-Boot-Krieg um die britischen Inseln an', place:'Nordsee und Nordatlantik', cause:'Die deutsche Führung wollte die britische Seeverbindung und Versorgung schwächen', consequence:'Handelsschiffe gerieten stärker in Gefahr', significance:'Der U-Boot-Krieg belastete die Beziehungen zu neutralen Staaten, besonders zu den USA' },
  { date:'22. April bis 25. Mai 1915', event:'Zweite Schlacht bei Ypern', place:'Flandern', cause:'Beide Seiten suchten einen Durchbruch an der Westfront', consequence:'Deutschland setzte in großem Umfang Chlorgas ein', significance:'Der Einsatz chemischer Waffen wurde zu einem besonders gefürchteten Merkmal des Krieges' },
  { date:'25. April 1915', event:'Landung auf Gallipoli', place:'Dardanellen', cause:'Die Entente wollte die Meerengen öffnen und Druck auf das Osmanische Reich ausüben', consequence:'Die Landung entwickelte sich zu einem verlustreichen Stellungskrieg und endete mit dem Rückzug', significance:'Gallipoli zeigte die Schwierigkeiten amphibischer Operationen gegen vorbereitete Verteidigung' },
  { date:'7. Mai 1915', event:'Versenkung der Lusitania', place:'vor der irischen Küste', cause:'Der deutsche U-Boot-Krieg richtete sich gegen Schiffe in den Gewässern um Großbritannien', consequence:'Der Untergang forderte viele zivile Opfer, darunter US-Bürger', significance:'Das Ereignis verschärfte die amerikanische Ablehnung des deutschen U-Boot-Krieges' },
  { date:'23. Mai 1915', event:'Italien tritt auf Seiten der Entente in den Krieg ein', place:'Rom', cause:'Italien erwartete territoriale Gewinne und wandte sich gegen Österreich-Ungarn', consequence:'Eine neue Front entstand entlang der Alpen und am Isonzo', significance:'Der Krieg erhielt eine bedeutende zusätzliche Front in Südeuropa' },
  { date:'21. Februar bis 15. Dezember 1916', event:'Schlacht um Verdun', place:'Verdun', cause:'Die deutsche Führung wollte Frankreich an einem symbolisch wichtigen Ort militärisch zermürben', consequence:'Monatelange Kämpfe verursachten enorme Verluste ohne entscheidenden deutschen Durchbruch', significance:'Verdun wurde zum Symbol des Abnutzungskrieges' },
  { date:'31. Mai bis 1. Juni 1916', event:'Skagerrakschlacht', place:'Nordsee', cause:'Die deutsche Hochseeflotte versuchte Teile der britischen Grand Fleet zu stellen', consequence:'Beide Flotten erlitten schwere Verluste, die britische Seeblockade blieb jedoch bestehen', significance:'Es war die größte Seeschlacht des Ersten Weltkriegs' },
  { date:'1. Juli bis 18. November 1916', event:'Schlacht an der Somme', place:'Somme, Frankreich', cause:'Die Entente wollte die deutsche Front durchbrechen und zugleich Frankreich bei Verdun entlasten', consequence:'Die Offensive brachte nur begrenzte Geländegewinne bei sehr hohen Verlusten', significance:'Die Somme steht exemplarisch für den industriellen Abnutzungskrieg' },
  { date:'Juni bis September 1916', event:'Brussilow-Offensive', place:'Ostfront, vor allem Galizien', cause:'Russland wollte Österreich-Ungarn stark unter Druck setzen und seine Verbündeten entlasten', consequence:'Österreich-ungarische Truppen erlitten schwere Verluste und mussten verstärkt werden', significance:'Die Offensive war einer der größten russischen Erfolge des Krieges' },
  { date:'Januar 1917', event:'Zimmermann-Telegramm', place:'Berlin, Washington und Mexiko', cause:'Deutschland suchte für den Fall eines US-Kriegseintritts einen strategischen Druck auf die USA', consequence:'Die britische Weitergabe des Telegramms verstärkte die antideutsche Stimmung in den USA', significance:'Das Telegramm trug zum amerikanischen Weg in den Krieg bei' },
  { date:'6. April 1917', event:'Kriegseintritt der Vereinigten Staaten', place:'Washington, D.C.', cause:'Der uneingeschränkte U-Boot-Krieg und weitere Spannungen veränderten die amerikanische Politik', consequence:'Die USA erklärten Deutschland den Krieg und bauten eine große Expeditionsarmee auf', significance:'Der Eintritt der USA verschob langfristig das Kräfteverhältnis zugunsten der Entente' },
  { date:'März 1917', event:'Abdankung Zar Nikolaus II.', place:'Petrograd', cause:'Versorgungsprobleme, Kriegsbelastung und politische Proteste führten zur Februarrevolution', consequence:'Die Zarenherrschaft endete und eine Provisorische Regierung entstand', significance:'Russland durchlief mitten im Krieg einen grundlegenden politischen Umbruch' },
  { date:'7. November 1917', event:'Oktoberrevolution der Bolschewiki', place:'Petrograd', cause:'Kriegsmüdigkeit und politische Instabilität schwächten die Provisorische Regierung', consequence:'Die Bolschewiki übernahmen die Macht', significance:'Der Machtwechsel bereitete Russlands Austritt aus dem Krieg vor' },
  { date:'3. März 1918', event:'Frieden von Brest-Litowsk', place:'Brest-Litowsk', cause:'Die bolschewistische Regierung wollte den Krieg mit den Mittelmächten beenden', consequence:'Russland schied aus dem Ersten Weltkrieg aus und akzeptierte große Gebietsverluste', significance:'Deutschland konnte Kräfte von der Ostfront an die Westfront verlegen' },
  { date:'21. März 1918', event:'Beginn der deutschen Frühjahrsoffensive', place:'Westfront', cause:'Nach Russlands Ausscheiden wollte Deutschland vor dem vollen Eintreffen amerikanischer Kräfte eine Entscheidung erzwingen', consequence:'Die deutschen Armeen erzielten zunächst große Geländegewinne, wurden aber aufgehalten', significance:'Das Scheitern erschöpfte wichtige deutsche Reserven' },
  { date:'8. August 1918', event:'Beginn der alliierten Hunderttageoffensive', place:'Amiens und Westfront', cause:'Die deutschen Frühjahrsoffensiven waren erschöpft und die Alliierten verfügten über wachsende materielle Überlegenheit', consequence:'Die Mittelmächte wurden zunehmend zurückgedrängt', significance:'Die Offensive leitete die letzte Phase bis zum Waffenstillstand ein' },
  { date:'11. November 1918', event:'Waffenstillstand von Compiègne', place:'Compiègne, Frankreich', cause:'Militärische Niederlagen, Versorgungskrise und politische Umbrüche zwangen die deutsche Führung zu Verhandlungen', consequence:'Die Kampfhandlungen an der Westfront endeten', significance:'Der Waffenstillstand beendete die unmittelbaren Kämpfe, aber die Friedensordnung wurde erst danach ausgehandelt' },
];

const WWII_EVENTS: HistoryEvent[] = [
  { date:'30. Januar 1933', event:'Hitler wird deutscher Reichskanzler', place:'Berlin', cause:'Politische Instabilität, Wahlerfolge der NSDAP und konservative Machtkalküle ermöglichten die Ernennung', consequence:'Die NS-Führung begann rasch mit der Zerstörung der demokratischen Ordnung', significance:'Die Machtübernahme bildete die Voraussetzung für Diktatur, Verfolgung und spätere Expansionspolitik' },
  { date:'7. März 1936', event:'Einmarsch deutscher Truppen ins Rheinland', place:'Rheinland', cause:'Das NS-Regime wollte die Bestimmungen von Versailles und Locarno zurückdrängen', consequence:'Die Remilitarisierung blieb ohne militärische Gegenaktion Frankreichs oder Großbritanniens', significance:'Der Erfolg stärkte Hitlers Bereitschaft zu weiteren außenpolitischen Risiken' },
  { date:'März 1938', event:'Anschluss Österreichs an das Deutsche Reich', place:'Österreich', cause:'Das NS-Regime betrieb die Eingliederung Österreichs und setzte die österreichische Regierung unter starken Druck', consequence:'Österreich wurde in das Deutsche Reich eingegliedert', significance:'Die territoriale Expansion NS-Deutschlands beschleunigte sich' },
  { date:'29. September 1938', event:'Münchner Abkommen', place:'München', cause:'Hitler forderte das überwiegend deutschsprachige Sudetenland der Tschechoslowakei', consequence:'Die Tschechoslowakei musste die Sudetengebiete abtreten', significance:'Das Abkommen zeigte die Grenzen der damaligen Beschwichtigungspolitik' },
  { date:'23. August 1939', event:'Deutsch-sowjetischer Nichtangriffspakt', place:'Moskau', cause:'Deutschland wollte einen Zweifrontenkrieg beim Angriff auf Polen zunächst vermeiden, die Sowjetunion Zeit gewinnen', consequence:'Ein geheimes Zusatzprotokoll ordnete Teile Osteuropas Einflusssphären zu', significance:'Der Pakt erleichterte den deutschen Angriff auf Polen' },
  { date:'1. September 1939', event:'Deutscher Überfall auf Polen', place:'Polen', cause:'Die NS-Führung verfolgte aggressive territoriale Expansion und hatte den Nichtangriffspakt mit der Sowjetunion geschlossen', consequence:'Großbritannien und Frankreich erklärten Deutschland kurz darauf den Krieg', significance:'Der Angriff gilt als Beginn des Zweiten Weltkriegs in Europa' },
  { date:'17. September 1939', event:'Sowjetischer Einmarsch in Ostpolen', place:'Ostpolen', cause:'Das geheime Zusatzprotokoll des deutsch-sowjetischen Pakts sah sowjetische Einflussgebiete in Osteuropa vor', consequence:'Polen wurde zwischen Deutschland und der Sowjetunion aufgeteilt', significance:'Der polnische Staat verlor seine territoriale Kontrolle und ging in den Widerstand und ins Exil' },
  { date:'9. April 1940', event:'Deutscher Angriff auf Dänemark und Norwegen', place:'Dänemark und Norwegen', cause:'Deutschland wollte strategische Seewege und den Zugang zu schwedischem Eisenerz sichern', consequence:'Dänemark wurde rasch besetzt, in Norwegen dauerte der Kampf länger', significance:'Deutschland gewann wichtige Stützpunkte an der Nordsee und am Nordatlantik' },
  { date:'10. Mai 1940', event:'Deutscher Angriff im Westen', place:'Benelux und Frankreich', cause:'Die deutsche Führung wollte Frankreich und seine Verbündeten militärisch ausschalten', consequence:'Die deutschen Truppen durchbrachen über die Ardennen und schnitten alliierte Verbände ab', significance:'Der Feldzug führte innerhalb weniger Wochen zum Zusammenbruch Frankreichs' },
  { date:'22. Juni 1940', event:'Waffenstillstand zwischen Frankreich und Deutschland', place:'Compiègne', cause:'Die französischen Streitkräfte waren nach dem deutschen Westfeldzug militärisch geschlagen', consequence:'Nord- und Westfrankreich wurden besetzt, im Süden entstand das Vichy-Regime', significance:'Deutschland beherrschte nun einen großen Teil Westeuropas' },
  { date:'Juli bis Oktober 1940', event:'Luftschlacht um England', place:'Großbritannien', cause:'Deutschland wollte die britische Luftverteidigung schwächen und Voraussetzungen für eine mögliche Invasion schaffen', consequence:'Die deutsche Luftwaffe errang keine Luftherrschaft über Großbritannien', significance:'Großbritannien blieb im Krieg und eine deutsche Invasion fand nicht statt' },
  { date:'6. April 1941', event:'Deutscher Angriff auf Jugoslawien und Griechenland', place:'Balkan', cause:'Die Achsenmächte wollten ihre Stellung auf dem Balkan sichern', consequence:'Jugoslawien und Griechenland wurden besetzt', significance:'Der Balkan geriet weitgehend unter Achsenkontrolle' },
  { date:'22. Juni 1941', event:'Unternehmen Barbarossa', place:'Sowjetunion', cause:'NS-Deutschland plante einen ideologisch und wirtschaftlich motivierten Eroberungs- und Vernichtungskrieg im Osten', consequence:'Deutsche und verbündete Armeen drangen tief in die Sowjetunion ein', significance:'Der Krieg im Osten wurde zum größten und verlustreichsten Kriegsschauplatz Europas' },
  { date:'28. und 29. September 1941', event:'Massaker von Babyn Jar', place:'bei Kiew', cause:'Die nationalsozialistische Besatzungs- und Vernichtungspolitik radikalisierte den Massenmord an Juden in den besetzten sowjetischen Gebieten', consequence:'Einsatzgruppen und weitere Kräfte ermordeten Zehntausende jüdische Menschen', significance:'Babyn Jar steht für die massenhaften Erschießungen im Holocaust' },
  { date:'7. Dezember 1941', event:'Angriff auf Pearl Harbor', place:'Hawaii', cause:'Der Konflikt zwischen Japan und den USA über Expansion, Embargos und Macht im Pazifik eskalierte', consequence:'Die Vereinigten Staaten traten in den Krieg gegen Japan ein', significance:'Der Krieg wurde endgültig zu einem globalen Konflikt mit voller US-Beteiligung' },
  { date:'20. Januar 1942', event:'Wannsee-Konferenz', place:'Berlin', cause:'Die NS-Führung koordinierte die bereits laufende systematische Verfolgung und Ermordung der europäischen Juden', consequence:'Vertreter verschiedener Behörden stimmten organisatorische Aspekte der sogenannten Endlösung ab', significance:'Die Konferenz dokumentiert die bürokratische Koordination des Holocaust' },
  { date:'4. bis 7. Juni 1942', event:'Schlacht um Midway', place:'Zentralpazifik', cause:'Japan wollte die amerikanische Pazifikflotte weiter schwächen und Midway besetzen', consequence:'Japan verlor vier Flottenträger und erfahrene Besatzungen', significance:'Midway veränderte das strategische Kräfteverhältnis im Pazifik' },
  { date:'August 1942 bis Februar 1943', event:'Schlacht von Stalingrad', place:'Stalingrad an der Wolga', cause:'Die deutsche Sommeroffensive zielte auf die Wolga und die Ressourcen des Kaukasus', consequence:'Die deutsche 6. Armee wurde eingeschlossen und kapitulierte', significance:'Stalingrad war ein entscheidender Wendepunkt an der Ostfront' },
  { date:'23. Oktober bis 4. November 1942', event:'Zweite Schlacht von El Alamein', place:'Ägypten', cause:'Die Achsenkräfte bedrohten Ägypten und die britischen Verbindungen im Nahen Osten', consequence:'Britische und Commonwealth-Truppen zwangen die Achsenkräfte zum Rückzug', significance:'Die Schlacht leitete den Rückzug der Achsenmächte aus Nordafrika ein' },
  { date:'Juli 1943', event:'Alliierte Landung auf Sizilien', place:'Sizilien', cause:'Nach dem Sieg in Nordafrika wollten die Alliierten den Druck auf Italien erhöhen', consequence:'Die Alliierten eroberten Sizilien und Mussolinis Regime geriet in die Krise', significance:'Die Invasion öffnete den Weg zum italienischen Kriegsaustritt und zur Kampagne auf dem Festland' },
  { date:'6. Juni 1944', event:'Landung in der Normandie', place:'Normandie', cause:'Die Westalliierten wollten eine große Front in Westeuropa eröffnen', consequence:'Alliierte Truppen errichteten einen Brückenkopf und begannen die Befreiung Westeuropas', significance:'D-Day eröffnete die entscheidende westliche Landfront gegen Deutschland' },
  { date:'22. Juni 1944', event:'Operation Bagration', place:'Belarus', cause:'Die Sowjetunion wollte die deutsche Heeresgruppe Mitte zerschlagen und verlorenes Gebiet zurückerobern', consequence:'Die Heeresgruppe Mitte erlitt eine katastrophale Niederlage', significance:'Die Ostfront verschob sich weit nach Westen und Deutschlands militärische Lage verschlechterte sich drastisch' },
  { date:'27. Januar 1945', event:'Befreiung von Auschwitz', place:'Auschwitz-Birkenau', cause:'Die Rote Armee rückte im Zuge der Winteroffensive nach Westen vor', consequence:'Sowjetische Soldaten befreiten die verbliebenen Gefangenen', significance:'Die Befreiung wurde später zu einem zentralen Bezugspunkt des Holocaust-Gedenkens' },
  { date:'8. Mai 1945', event:'Kapitulation Deutschlands in Europa tritt in Kraft', place:'Europa', cause:'Deutschland war militärisch zusammengebrochen und Berlin gefallen', consequence:'Die Kampfhandlungen des Zweiten Weltkriegs in Europa endeten weitgehend', significance:'Der 8. Mai markiert das Ende der NS-Herrschaft und des Krieges in Europa' },
  { date:'2. September 1945', event:'Formelle Kapitulation Japans', place:'Tokio-Bucht', cause:'Nach schweren militärischen Niederlagen, den Atombombenabwürfen und dem sowjetischen Kriegseintritt akzeptierte Japan die Kapitulation', consequence:'Die Kapitulationsurkunde wurde unterzeichnet', significance:'Der Zweite Weltkrieg endete damit auch formell im Pazifik' },
];

const CHECHEN_EVENTS: HistoryEvent[] = [
  { date:'1818', event:'Gründung der russischen Festung Grosny', place:'am Fluss Sunscha im Nordkaukasus', cause:'Das Russische Reich baute seine militärische Präsenz im Nordkaukasus aus', consequence:'Die Festung wurde ein wichtiger russischer Militärstützpunkt und später zum Kern der Stadt Grosny', significance:'Die Gründung steht für die zunehmende imperiale Durchdringung des tschetschenischen Raums' },
  { date:'1817 bis 1864', event:'Kaukasuskrieg', place:'Nordkaukasus', cause:'Das Russische Reich versuchte seine Herrschaft im Nordkaukasus auszuweiten, während verschiedene lokale Gesellschaften Widerstand leisteten', consequence:'Der langjährige Krieg führte zu starken Verlusten, Vertreibungen und tiefen politischen Veränderungen', significance:'Der Kaukasuskrieg prägte die Beziehungen zwischen der Region und dem Russischen Reich langfristig' },
  { date:'1834', event:'Imam Schamil übernimmt die Führung des Kaukasischen Imamats', place:'Dagestan und Tschetschenien', cause:'Nach dem Tod früherer Anführer brauchte der Widerstand eine neue zentrale Führung', consequence:'Schamil organisierte über Jahrzehnte Widerstand gegen die russische Expansion', significance:'Seine Herrschaft verband Teile Dagestans und Tschetscheniens in einem organisierten politischen und militärischen System' },
  { date:'1859', event:'Imam Schamil ergibt sich russischen Truppen', place:'Gunib, Dagestan', cause:'Nach jahrelangem Krieg und verstärktem russischem militärischem Druck war seine Lage unhaltbar geworden', consequence:'Das Kaukasische Imamat verlor seine zentrale Führung', significance:'Die Kapitulation markierte das Ende einer entscheidenden Phase des organisierten Widerstands' },
  { date:'1864', event:'Ende des Kaukasuskrieges', place:'Westlicher und nördlicher Kaukasus', cause:'Nach Schamils Kapitulation setzte Russland die militärische Unterwerfung anderer Widerstandsgebiete fort', consequence:'Das Russische Reich festigte seine Kontrolle über den Nordkaukasus', significance:'1864 gilt als Schlusspunkt des langen Kaukasuskrieges' },
  { date:'30. November 1922', event:'Gründung des Tschetschenischen Autonomen Gebiets', place:'Russische SFSR', cause:'Die frühe Sowjetunion ordnete nationale Territorien im Nordkaukasus administrativ neu', consequence:'Tschetschenien erhielt den Status eines autonomen Gebiets innerhalb der Russischen SFSR', significance:'Die Entscheidung schuf eine neue sowjetische Verwaltungsstruktur für das tschetschenische Gebiet' },
  { date:'15. Januar 1934', event:'Zusammenschluss des tschetschenischen und inguschischen Autonomen Gebiets', place:'Nordkaukasus', cause:'Die sowjetische Führung fasste benachbarte autonome Gebiete administrativ zusammen', consequence:'Es entstand das Tschetschenisch-Inguschische Autonome Gebiet', significance:'Die Vereinigung bereitete die spätere Tschetschenisch-Inguschische ASSR vor' },
  { date:'1936', event:'Gründung der Tschetschenisch-Inguschischen ASSR', place:'Russische SFSR', cause:'Eine sowjetische Verfassungs- und Verwaltungsreform hob den Status des gemeinsamen Gebiets an', consequence:'Das Gebiet erhielt den Rang einer Autonomen Sozialistischen Sowjetrepublik', significance:'Die ASSR bestand bis zu ihrer Auflösung während der Deportationen von 1944' },
  { date:'23. Februar 1944', event:'Beginn der Deportation von Tschetschenen und Inguschen', place:'Tschetschenisch-Inguschische ASSR', cause:'Die stalinistische Führung beschuldigte ganze Bevölkerungsgruppen kollektiv der Illoyalität und Kollaboration', consequence:'Hunderttausende Menschen wurden nach Zentralasien und in andere Regionen der Sowjetunion deportiert', significance:'Die Deportation verursachte tiefgreifende demografische, soziale und menschliche Folgen' },
  { date:'1944', event:'Auflösung der Tschetschenisch-Inguschischen ASSR', place:'Sowjetunion', cause:'Die Deportation der tschetschenischen und inguschischen Bevölkerung wurde mit einer administrativen Neuordnung verbunden', consequence:'Das autonome Gebiet wurde aufgelöst und sein Territorium neu verteilt', significance:'Die staatliche Autonomie verschwand bis zur Rehabilitierung und Wiederherstellung' },
  { date:'Februar 1956', event:'Chruschtschow verurteilt die Deportationen in seiner Geheimrede', place:'Moskau', cause:'Nach Stalins Tod begann eine teilweise Abkehr von stalinistischen Repressionen', consequence:'Die pauschale Bestrafung deportierter Völker wurde offiziell kritisiert', significance:'Die Entstalinisierung bereitete die politische Rehabilitierung und Rückkehr vieler Deportierter vor' },
  { date:'1957', event:'Wiederherstellung der Tschetschenisch-Inguschischen ASSR', place:'Nordkaukasus', cause:'Die sowjetische Führung rehabilitierte Tschetschenen und Inguschen und erlaubte die Rückkehr', consequence:'Die autonome Republik wurde wieder eingerichtet und viele Familien kehrten zurück', significance:'Die Rückkehr veränderte die Bevölkerungsstruktur und politische Entwicklung der Region erneut' },
  { date:'1991', event:'Tschetschenische Unabhängigkeitserklärung', place:'Grosny', cause:'Der Zerfall der Sowjetunion löste in vielen Regionen Debatten über staatliche Souveränität aus', consequence:'Die Führung in Grosny erklärte die Unabhängigkeit, die von Moskau nicht anerkannt wurde', significance:'Die ungeklärte Statusfrage führte zu einer tiefen politischen Konfrontation mit der Russischen Föderation' },
  { date:'11. Dezember 1994', event:'Beginn des Ersten Tschetschenienkrieges', place:'Tschetschenien', cause:'Der Konflikt um die von Moskau nicht anerkannte Unabhängigkeit eskalierte militärisch', consequence:'Russische Streitkräfte rückten in Tschetschenien ein und es kam zu schweren Kämpfen', significance:'Der Krieg verursachte große Zerstörungen und endete 1996 ohne dauerhafte Statuslösung' },
  { date:'August 1996', event:'Abkommen von Chassawjurt', place:'Chassawjurt, Dagestan', cause:'Beide Seiten suchten nach schweren Verlusten einen Weg zur Beendigung der Kämpfe', consequence:'Die größeren Kampfhandlungen des Ersten Tschetschenienkrieges endeten', significance:'Die Frage des endgültigen politischen Status wurde vertagt' },
  { date:'Januar 1997', event:'Präsidentschaftswahl in Tschetschenien', place:'Tschetschenien', cause:'Nach dem Ende des Ersten Krieges sollte eine politische Ordnung geschaffen werden', consequence:'Aslan Maschadow gewann die international beobachtete Wahl', significance:'Die Wahl schuf eine zivile Führung, konnte aber die tiefen Sicherheits- und Staatsprobleme nicht vollständig lösen' },
  { date:'1999', event:'Beginn des Zweiten Tschetschenienkrieges', place:'Tschetschenien und Nordkaukasus', cause:'Bewaffnete Konflikte in Dagestan und eine schwere Sicherheitskrise verschärften die Konfrontation zwischen Moskau und tschetschenischen Kräften', consequence:'Russische Streitkräfte begannen eine neue groß angelegte Militärkampagne', significance:'Der Krieg veränderte die politische Ordnung Tschetscheniens dauerhaft und führte zu erneuter massiver Flucht und Zerstörung' },
];

const JAPAN_EVENTS: HistoryEvent[] = [
  { date:'1603', event:'Beginn des Tokugawa-Shogunats', place:'Edo', cause:'Tokugawa Ieyasu hatte seine politische und militärische Vorrangstellung nach Jahrzehnten innerer Konflikte gefestigt', consequence:'Eine lange Phase zentraler Herrschaft durch die Tokugawa begann', significance:'Die Tokugawa-Zeit prägte Japans politische Ordnung über zweieinhalb Jahrhunderte' },
  { date:'1630er Jahre', event:'Verschärfung der Politik kontrollierter Außenkontakte', place:'Japan', cause:'Das Tokugawa-Shogunat wollte ausländischen politischen und religiösen Einfluss begrenzen und den Außenhandel kontrollieren', consequence:'Auslandsreisen und Handel wurden stark reguliert, einige Kontakte blieben jedoch bestehen', significance:'Die Politik formte Japans internationale Beziehungen bis zur Mitte des 19. Jahrhunderts' },
  { date:'8. Juli 1853', event:'Ankunft der amerikanischen Flotte unter Matthew Perry', place:'Uraga-Bucht bei Edo', cause:'Die Vereinigten Staaten wollten japanische Häfen für Versorgung und Handel öffnen', consequence:'Das Shogunat geriet unter starken diplomatischen Druck', significance:'Die Ankunft Perrys beschleunigte die Krise der Tokugawa-Ordnung' },
  { date:'31. März 1854', event:'Vertrag von Kanagawa', place:'Kanagawa', cause:'Nach Perrys Rückkehr akzeptierte das Shogunat begrenzte Öffnungen gegenüber den USA', consequence:'Japan öffnete ausgewählte Häfen für amerikanische Schiffe', significance:'Der Vertrag war ein wichtiger Schritt aus der außenpolitischen Abschließung' },
  { date:'29. Juli 1858', event:'Harris-Vertrag zwischen Japan und den USA', place:'Edo', cause:'Westliche Mächte forderten weitergehende Handelsrechte und diplomatische Zugänge', consequence:'Weitere Häfen wurden geöffnet und ausländische Rechte ausgeweitet', significance:'Die ungleichen Vertragsbedingungen verstärkten innenpolitische Spannungen' },
  { date:'7. März 1866', event:'Satsuma-Choshu-Bündnis', place:'Japan', cause:'Gegner des Shogunats suchten eine gemeinsame politische und militärische Basis', consequence:'Zwei einflussreiche Domänen koordinierten ihren Widerstand gegen das Tokugawa-Shogunat', significance:'Das Bündnis erleichterte den späteren Sturz der Tokugawa-Herrschaft' },
  { date:'9. November 1867', event:'Tokugawa Yoshinobu gibt die politische Regierungsgewalt zurück', place:'Kyoto', cause:'Das Shogunat stand unter starkem Reform- und Oppositionsdruck', consequence:'Yoshinobu bot die Rückgabe der Regierungsgewalt an den Kaiserhof an', significance:'Der Schritt beschleunigte den Übergang zur neuen Meiji-Regierung' },
  { date:'3. Januar 1868', event:'Proklamation der Wiederherstellung kaiserlicher Regierungsgewalt', place:'Kyoto', cause:'Anti-Tokugawa-Kräfte wollten eine neue zentralisierte Staatsordnung schaffen', consequence:'Eine neue Regierung im Namen des Kaisers wurde gebildet', significance:'Das Ereignis markiert den politischen Beginn der Meiji-Restauration' },
  { date:'1868 bis 1869', event:'Boshin-Krieg', place:'Japan', cause:'Anhänger der neuen Meiji-Regierung und Kräfte des ehemaligen Shogunats stritten um die politische Macht', consequence:'Die Meiji-Seite setzte sich militärisch durch', significance:'Der Krieg beseitigte den wichtigsten bewaffneten Widerstand gegen die neue Zentralregierung' },
  { date:'1871', event:'Aufhebung der Han und Einrichtung von Präfekturen', place:'Japan', cause:'Die Meiji-Regierung wollte die politische Zersplitterung der alten Domänenordnung überwinden', consequence:'Die ehemaligen Fürstentümer wurden durch zentral kontrollierte Präfekturen ersetzt', significance:'Die Reform stärkte den modernen Zentralstaat' },
  { date:'23. Dezember 1871', event:'Abreise der Iwakura-Mission', place:'Yokohama', cause:'Die neue Regierung wollte westliche Institutionen studieren und eine Revision ungleicher Verträge vorbereiten', consequence:'Hochrangige Politiker bereisten die USA und Europa bis 1873', significance:'Die Mission beeinflusste Japans Modernisierungs- und Institutionenpolitik' },
  { date:'1872', event:'Einführung eines modernen landesweiten Schulsystems', place:'Japan', cause:'Die Meiji-Regierung betrachtete Bildung als Grundlage für Staatsaufbau und Modernisierung', consequence:'Der Staat begann ein nationales Bildungssystem aufzubauen', significance:'Bildung wurde zu einem wichtigen Motor gesellschaftlicher und wirtschaftlicher Veränderung' },
  { date:'1873', event:'Einführung der allgemeinen Wehrpflicht', place:'Japan', cause:'Die Regierung wollte eine moderne nationale Armee anstelle traditioneller Kriegerverbände schaffen', consequence:'Männer wurden nach neuen gesetzlichen Regeln zum Militärdienst herangezogen', significance:'Die Wehrpflicht stärkte den zentralen Staat und veränderte die soziale Rolle der Samurai' },
  { date:'1877', event:'Satsuma-Rebellion', place:'Kagoshima und Kyushu', cause:'Unzufriedene ehemalige Samurai lehnten Teile der Meiji-Reformen und den Verlust ihrer bisherigen Stellung ab', consequence:'Die Regierungstruppen besiegten die Rebellion', significance:'Die Niederlage beendete den letzten großen bewaffneten Samurai-Aufstand gegen die Meiji-Regierung' },
  { date:'11. Februar 1889', event:'Verkündung der Meiji-Verfassung', place:'Japan', cause:'Die Regierung wollte einen modernen Verfassungsstaat mit nationalen Institutionen schaffen', consequence:'Japan erhielt eine schriftliche Verfassung mit Parlament und monarchischer Exekutive', significance:'Die Verfassung strukturierte den Staat bis nach dem Zweiten Weltkrieg' },
  { date:'29. November 1890', event:'Eröffnung des ersten Reichstags', place:'Tokio', cause:'Die Meiji-Verfassung sah ein nationales Parlament vor', consequence:'Das parlamentarische System nahm seine Arbeit auf', significance:'Der Reichstag schuf eine neue Arena für Parteien, Haushalt und Gesetzgebung' },
  { date:'1894 bis 1895', event:'Erster Japanisch-Chinesischer Krieg', place:'Korea, China und umliegende Seegebiete', cause:'Japan und China konkurrierten um politischen Einfluss in Korea', consequence:'Japan siegte militärisch und gewann erheblichen regionalen Einfluss', significance:'Der Krieg zeigte den schnellen Aufstieg Japans zur regionalen Großmacht' },
  { date:'1904 bis 1905', event:'Russisch-Japanischer Krieg', place:'Mandschurei und Seegebiete Ostasiens', cause:'Russland und Japan konkurrierten um Einfluss in Korea und der Mandschurei', consequence:'Japan besiegte das Russische Reich und gewann internationale Anerkennung seiner Stellung', significance:'Der Sieg veränderte das Machtgleichgewicht in Ostasien' },
  { date:'1910', event:'Annexion Koreas durch Japan', place:'Koreanische Halbinsel', cause:'Japan hatte seinen politischen und militärischen Einfluss auf Korea schrittweise ausgebaut', consequence:'Korea wurde formal in das Japanische Kaiserreich eingegliedert', significance:'Die Kolonialherrschaft prägte die japanisch-koreanischen Beziehungen langfristig' },
  { date:'1931', event:'Besetzung der Mandschurei durch Japan', place:'Mandschurei', cause:'Japanische Militärkreise wollten ihren Einfluss und Zugriff auf Ressourcen in Nordostchina ausweiten', consequence:'Japan errichtete dort später den abhängigen Staat Mandschukuo', significance:'Die Expansion verschärfte Japans Konflikt mit China und der internationalen Ordnung' },
  { date:'7. Juli 1937', event:'Ausweitung des Krieges zwischen Japan und China', place:'China', cause:'Ein militärischer Zwischenfall nahe der Marco-Polo-Brücke eskalierte bestehende Spannungen', consequence:'Es begann ein umfassender Krieg zwischen Japan und China', significance:'Der Krieg band große japanische Kräfte und wurde später Teil des breiteren Zweiten Weltkriegs in Asien' },
  { date:'7. Dezember 1941', event:'Angriff auf Pearl Harbor', place:'Hawaii', cause:'Der Konflikt mit den USA über Japans Expansion und wirtschaftliche Sanktionen war eskaliert', consequence:'Die Vereinigten Staaten traten in den Krieg gegen Japan ein', significance:'Der Pazifikkrieg weitete sich schlagartig zu einem umfassenden Krieg zwischen Japan und den USA aus' },
  { date:'August bis 2. September 1945', event:'Japan akzeptiert und unterzeichnet die Kapitulation', place:'Japan und Tokio-Bucht', cause:'Militärische Niederlagen, Atombombenabwürfe und der sowjetische Kriegseintritt machten eine Fortsetzung des Krieges aussichtslos', consequence:'Japan beendete den Krieg und begann eine alliierte Besatzungszeit', significance:'Die Kapitulation leitete einen tiefgreifenden politischen und gesellschaftlichen Neubeginn ein' },
  { date:'3. Mai 1947', event:'Neue japanische Verfassung tritt in Kraft', place:'Japan', cause:'Nach der Kriegsniederlage wurden politische Institutionen unter der alliierten Besatzung grundlegend reformiert', consequence:'Parlamentarische Demokratie, Grundrechte und eine neue verfassungsrechtliche Ordnung wurden verankert', significance:'Die Verfassung bildet bis heute die Grundlage des politischen Systems Japans' },
  { date:'28. April 1952', event:'Ende der alliierten Besatzung Japans', place:'Japan', cause:'Der Friedensvertrag von San Francisco trat in Kraft', consequence:'Japan gewann seine volle staatliche Souveränität zurück', significance:'Das Ende der Besatzung markierte Japans Rückkehr als eigenständiger Akteur in die internationale Staatengemeinschaft' },
];

export const HISTORY_QUESTIONS: HistoryQuestion[] = [
  ...buildTopic(WWI_EVENTS, 'Geschichte Erster Weltkrieg', 10000, 100, 50, 'National WWI Museum and Memorial, Key Dates; Imperial War Museums'),
  ...buildTopic(WWII_EVENTS, 'Geschichte Zweiter Weltkrieg', 11000, 100, 50, 'United States Holocaust Memorial Museum, World War II Dates and Timeline'),
  ...buildTopic(CHECHEN_EVENTS, 'Geschichte Tschetschenien', 12000, 50, 30, 'Library of Congress, Revelations from the Russian Archives; US Army War College'),
  ...buildTopic(JAPAN_EVENTS, 'Geschichte Japan', 13000, 100, 50, 'National Diet Library Japan, Modern Japan in Archives'),
];
